### ISSUE TITLE
[MacOS]No available formula with the name "clang"

### ISSUE THREAD

**Issue by forchain** [LuoZijun/exodus#11]
~/github.com/LuoZijun/exodus (master ✔) ᐅ brew install git curl wget clang

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, caskroom/cask).
==> Updated Formulae
frugal                                  gopass                                  hlint

Error: No available formula with the name "clang"

**Comment by forchain** [comment]
@LuoZijun 不好意思，忘记Assign 你了，这里@你一下

**Comment by LuoZijun** [comment]
@forchain 那就把clang 移除，有Xcode 应该就有clang 。
