### ISSUE TITLE
[MacOS]Could not compile `netif`

### ISSUE THREAD

**Issue by forchain** [LuoZijun/exodus#12]
Compiling netif v0.1.0 (file:///Users/Tony/github.com/LuoZijun/exodus/netif)
error: invalid suffix `DWORD` for numeric literal
   --> netif/src/sys/windows/iphlpapi.rs:221:30
    |
221 |     MIB_IPROUTE_TYPE_OTHER = 1DWORD,
    |                              ^^^^^^
    |
    = help: the suffix must be one of the integral types (`u32`, `isize`, etc)

error: invalid suffix `DWORD` for numeric literal
   --> netif/src/sys/windows/iphlpapi.rs:230:25
    |
230 |     MIB_IPPROTO_OTHER = 1DWORD,
    |                         ^^^^^^
    |
    = help: the suffix must be one of the integral types (`u32`, `isize`, etc)

error: expected one of `!` or `::`, found `struct`
   --> netif/src/sys/windows/iphlpapi.rs:270:9
    |
270 | typedef struct _MIB_IPFORWARD_ROW2 {
    |         ^^^^^^ expected one of `!` or `::` here

error: Could not compile `netif`.

**Comment by forchain** [comment]
@LuoZijun 奇怪了，这个文件是应该在Windows下面才编译的吗，但是我是在Mac上，需要更改什么设置么

**Comment by LuoZijun** [comment]
呃，不好意思，这个属于语法错误，昨天临时弄上去的。

你可以在本地手动把这两行的 DWORD 删掉就好了。

**Comment by forchain** [comment]
临时方案：
将netif/src/sys/windows/iphlpapi.rs中
1 1DWORD改成1u32
2 把270～286注释掉
