### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by luckypoem** [LuoZijun/exodus#13]
我运行 `sudo ./vpn_macos --server-addr my-vps-ip:9050 --disable-crypto`

会显示：

>> 

    [2018-01-14 21:17:31.686324000  INFO] vpn use default interface "en0"
    [2018-01-14 21:17:31.687804000  INFO] vpn bind on interface en0 192.168.1.3:9050
    [2018-01-14 21:17:31.687855000  INFO] vpn connect to your-vps-ip:9050
    [2018-01-14 21:17:31.868511000  INFO] vpn tun device running at 172.16.0.8 --> 172.16.0.1 netmask: 255.0.0.0
    add host your-vps-ip: gateway 192.168.1.1
    delete net default
    add net default: gateway 172.16.0.8
    [2018-01-14 21:17:31.903760000  INFO] vpn auto config routing table    [OK]
    [2018-01-14 21:17:31.993942000  INFO] vpn auto config dns server       [OK]
    [2018-01-14 21:17:31.994234000  INFO] vpn Ready for transmission. 

上面的 `add host your-vps-ip: gateway 192.168.1.1` 是自动显示的。

## vpn-ws 问题

Link: https://github.com/unbit/vpn-ws/issues/6

我在另一台服务器上安装了`vpn-ws`, 且能在mac上，成功连接这个 `vpn-ws` , 
但在我的mac机器中的浏览器里就是翻墙失败，访问 www.ipaddress.com , 
显示的是我的isp分配给我的ip, 而非我的vps的IP。

可能是路由未设置好。

我在mac上，运行 `sudo  route add -host my-vps-ip gateway 192.168.1.1`
显示：

> route: bad address: gateway

怎么回事？这个命令不正确吗？该怎么写这条命令？

非常感谢你的答复。

**Comment by LuoZijun** [comment]
@luckypoem 

1. 请清除一切你自己手动设置的路由表。（如:  `sudo route add -host my-vps-ip gateway 192.168.1.1` ）
2. `vpn-ws` 这个程序的服务端当然不能和这个项目的 `vpn` 客户端互相沟通，通讯协议不一样。
3. `vpn-ws` 这个程序的客户端和服务端之间的互连可能出现的问题，建议你直接询问这个项目的作者，我本人并没有使用过该项目代码，亦不清楚具体细节。

**Comment by LuoZijun** [comment]
@luckypoem 

很抱歉，这个项目只接受跟这个项目相关的问题。对于你的 `vpn-ws` 程序出现的问题，请直接咨询该项目的维护者或者作者。

**Comment by luckypoem** [comment]
@LuoZijun 
"vpn use default interface "en0" ",这里怎么是使用默认的网卡en0，而非/dev/tap0?
意思是我事先无需安装tuntaposx这个程序？
网卡en0是怎么来的？所有的mac机器本身已自带吗？

我在mac上运行ifconfig, 显示的结果里确实有en0

**Comment by LuoZijun** [comment]
你无需安装任何其它的软件。
en0 代表着你的网络结构环境处于一个以太网环境。如果你的网络环境不是以太网那就没有这个en0。

**Comment by luckypoem** [comment]
@LuoZijun 

```
vpn use default interface "en0"

vpn bind on interface en0 192.168.1.3:9050

vpn connect to your-vps-ip:9050

vpn tun device running at 172.16.0.8 --> 172.16.0.1 netmask: 255.0.0.0

add host your-vps-ip: gateway 192.168.1.1

delete net default

add net default: gateway 172.16.0.8

vpn auto config routing table

vpn auto config dns server

```

这9行对应9条命令，对吗？如果手动运行命令的话，该如何写这9条命令呢？

非常感谢你的不吝赐教。想借鉴一下

**Comment by LuoZijun** [comment]
@luckypoem 这涉及底层编程，不完全是 命令行调用。

使用命令行调用只能获取部分不稳定信息，如果你需要手动输入的话，参考 `route` 命令。

DNS 方面，类 Unix 系统使用的是文件配置，一般在 `/etc/resolv.conf` 。
`macOS` 系统使用数据库存储，`/etc/resolv.conf` 为只读信息，修改需要调用 `networksetup` 命令。


代码可以参考:

*    [src/syscfg.rs](https://github.com/LuoZijun/exodus/blob/master/src/syscfg.rs)
*    [netif/src/interface.rs](https://github.com/LuoZijun/exodus/blob/master/netif/src/interface.rs)
*    [netif/src/route.rs](https://github.com/LuoZijun/exodus/blob/master/netif/src/route.rs)

**Comment by luckypoem** [comment]
如何使用networksetup命令修改mac的dns服务器地址？我运行networksetup -h ,跳出一大堆选项，不知该选哪个好。
谢谢回复

**Comment by LuoZijun** [comment]
```bash
networksetup -listnetworkserviceorder       # 获取 `Network Server Order`
networksetup -getdnsservers "Wi-Fi"         # 查看当前已设定的DNS (不包含默认 DNS)
networksetup -setdnsservers "Wi-Fi" 8.8.8.8 # 设置新的DNS
networksetup -setdnsservers "Wi-Fi" "Empty" # DNS 复原
```

**Comment by luckypoem** [comment]
@LuoZijun 

我看见你也fork了kytan: `https://github.com/LuoZijun/kytan` 。

我使用`networksetup`命令修改了mac的dns服务器地址为`8.8.8.8`:

```
yudeMacBook-Air:~ brite$ networksetup -getdnsservers Wi-Fi
8.8.8.8
yudeMacBook-Air:~ brite$
```

但是用kytan访问被封的网站时，火狐浏览器的左下角依旧显示：

>    looking up some-blocked-domain.com

网站还是打不开，显示：

> The connection was reset。

你可否考虑添加一下它这个`kytan`的反`DNS`污染功能，推出改进版的`kytan`呢？
非常感谢你！
ref: https://github.com/changlan/kytan/issues/26

**Comment by LuoZijun** [comment]
@luckypoem 

没有这个考虑。
