### ISSUE TITLE
请教--disable-crypto

### ISSUE THREAD

**Issue by forchain** [LuoZijun/exodus#14]
1. 请问 `VPN客户端` 中的参数 `--disable-crypto` 是不是说通道是没有加密的？
2. `VPN客户端` 和 `VPN服务器` 之间的通讯是否很容易被流量控制？

**Comment by LuoZijun** [comment]
## 关于启用加密和压缩

当前的确默认不启用 `加密` 和 `压缩` 。之所以不启用，是因为还没有设计协议。
目前的工作重点在 跨平台的支持，特别是 `Windows` 和 `iOS` 这两个平台。

*未启用的加密和压缩代码:*

*    [src/crypto.rs](https://github.com/LuoZijun/exodus/blob/master/src/crypto.rs)
*    [src/compression.rs](https://github.com/LuoZijun/exodus/blob/master/src/compression.rs)


## 关于 流量控制

`流量控制` 这个一般出现在 `UDP` 协议上，一些 ISP 出于商业逻辑，
会对 `UDP` 的传输流量进行干涉，极端情况下直接 `重置` 该连接。

**ISP 为什么要做 `UDP流控` ？**

典型的场景:

> ISP 提供商承诺了 `100Mbps` 速度的带宽，但是这个带宽是好多人在一起共享使用的。
> ISP 自然不希望其中有一个人把带宽资源给耗尽。
> 那么办法自然就是流量管控。

**ISP 为什么不能让共享使用的人平分带宽呢？**

> 大厂基本就是这么实现的，但是小服务商没有这个能力。他们的流量管控介入是根据旁路观测的数据再决定是否介入，而介入也是非常粗暴的直接 `重置` 连接。

**有哪些不做流量管控的 ISP ？**

*云服务方面:*

> 据我的使用经验，谷歌的云服务( `Google Cloud` )就不做这个限制。

*家庭个人带宽方面:*

> 一般一级 ISP 也不会做这个限制，比如 `中国电信` 和 `中国联通` 。
