### ISSUE TITLE
运行“./vpnd_linux --tun-network 172.16.0.0/16” 遇错

### ISSUE THREAD

**Issue by luckypoem** [LuoZijun/exodus#16]
```
root@sk:~# ./vpnd_linux --tun-network 172.16.0.0/16
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `5`', src/syscfg.rs:99:28
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@sk:~# 
```

如何解决？

**Comment by LuoZijun** [comment]
@luckypoem 

请贴出你的路由表（ ‘ip route’ 命令）。

以及描述下你的系统环境（发行版，内核，等）。

**Comment by luckypoem** [comment]
```
root@sk:~# ip route
default via 107.155.113.1 dev eth0 onlink 
10.255.32.0/24 dev eth1  proto kernel  scope link  src 10.255.32.11 
107.155.113.0/25 dev eth0  proto kernel  scope link  src my-vps-ip
root@sk:~#
root@sk:~# cat /etc/issue.net
Ubuntu 16.04.1 LTS
root@sk:~# uname -a
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@sk:~#
```

**Comment by LuoZijun** [comment]
在release页面下载最新版再试试。

**Comment by luckypoem** [comment]
在新的服务器上下载了alpha-2版，并运行中：
```
root@sk:~# ps aux|grep vpnd_linux
root     21208  0.0  0.8  20108  8976 pts/3    Sl   10:38   0:00 ./vpnd_linux-a2 --tun-network 172.16.0.0/16
root     21358  0.0  0.0  14224   964 pts/1    S+   10:52   0:00 grep --color=auto vpnd_linux
root@sk:~#
```

在mac上，也下载了alpha-2版的vpn_macos,并运行之：

```bash
yudeMacBook-Air:~ brite$ sudo ./vpn_macos --server-addr my-vps-ip:9050 --disable-crypto
```

显示：

```
Password:
[2018-01-31 18:51:28.953374000  INFO] vpn use default interface "en0"
[2018-01-31 18:51:28.954343000  INFO] vpn bind on interface en0 192.168.1.3:9050
[2018-01-31 18:51:28.954395000  INFO] vpn connect to my-vps-ip:9050
```

然后下面就没有内容显示了。
这说明什么？说明连不上服务器的9050端口吗

**Comment by LuoZijun** [comment]
是的。请检查服务器防火墙是否有开放该端口。

**Comment by luckypoem** [comment]
在centos7下，无论下载alpha-3,aplpha-2,alpha-1,还是alpha版本，运行后都遇错：
[root@hs ~]# ./vpnd_linux --tun-network 172.16.0.0/16
[2018-02-13 09:34:14.095319178  INFO] vpnd bind at my-vps-ip:9050 ...
[2018-02-13 09:34:14.095408008  INFO] vpnd tun device running at: 172.16.0.1 --> 0.0.0.0 netmask: 255.255.0.0
net.ipv4.ip_forward = 1
thread 'main' panicked at 'failed to execute process: Error { repr: Os { code: 2, message: "No such file or directory" } }', libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
[root@hs ~]# 

如何解决？谢谢你

**Comment by luckypoem** [comment]
我的centos7是64位：
[root@hs ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 
[root@hs ~]# uname -a
Linux 2.6.32-042stab126.1 #1 SMP Wed Nov 15 20:14:46 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@hs ~]#

**Comment by LuoZijun** [comment]
不支持Centos系列系统。

**Comment by luckypoem** [comment]
@LuoZijun 
不过我觉得你这个exodus程序不支持Centos系列系统，这有点奇怪。
像这种linux上的可执行文件难道不是在任何linux发行版（当然需要是同样的bit数，比如都为64位系统）上都能运行的吗？

比如那个kytan程序，我把其可执行文件（https://github.com/changlan/kytan/releases/download/v0.1.0/kytan-v0.1.0-x86_64-unknown-linux-gnu）分别下载到了一个debian vps和centos vps,在它们上面都能成功运行。但是你这个exodus程序却不支持Centos系列系统，这是为什么？

**Comment by LuoZijun** [comment]
@luckypoem 

支持 `CentOS` 当然不会有太大的技术问题。之所以没有支持是因为我没有相关环境。
另外我个人也不是特别欣赏这个发型版。
我个人认为支持 `Windows` 远比支持 `CentOS` 重要。
