### ISSUE TITLE
Exodus vpnd client failing 

### ISSUE THREAD

**Issue by surereddy** [LuoZijun/exodus#18]
Hello sir thank you i could build vpnd which out any errors but i try for client i have an 
error: Found argument '--server-addr' which wasn't expected, or isn't valid in this context
vpnd --server-addr 5.189.143.25:40000 --disable-crypto &
USAGE:
    vpnd [FLAGS] [OPTIONS] --tun-network <tun-network>

For more information try --help

**Comment by surereddy** [comment]
after build there no vpn  client found only vpnd can u please help me

**Comment by LuoZijun** [comment]
> try for client i have an `error: Found argument '--server-addr' which wasn't expected`

Please give me more infomation.

*    System info
*    CMD line
*    Full error message


> after build there no vpn client found only vpnd

    cargo build --bin vpn
    cargo build --bin vpnd
    cp target/debug/vpn vpn
    cp target/debug/vpnd vpnd
    sudo ./vpn --server-addr SERVER_IP:SERVER_PORT --disable-crypto

**Comment by surereddy** [comment]
Thank you so much i could build .I will test and update thank's a lot
