### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by surereddy** [LuoZijun/exodus#19]
hello sir how can use it can you please give me config please

**Comment by LuoZijun** [comment]
See `README.rst`

**Comment by surereddy** [comment]
i have read it show to use like this cd exodus
# VPN Server
sudo ./vpnd --tun-network 172.16.0.0/16

# VPN Client
sudo ./vpn --server-addr YOUR_VPN_SERVER_IPV4_ADDR:YOUR_VPN_SERVER_UDP_PORT --disable-crypto
 but for client there is not tun device  .I cannot understand how it will connect sir.

**Comment by LuoZijun** [comment]
1. How to use ?

    sudo ./vpnd --tun-network 172.16.0.0/16
    sudo ./vpn --server-addr YOUR_VPN_SERVER_IPV4_ADDR:YOUR_VPN_SERVER_UDP_PORT --disable-crypto

2. How It Works ?

    https://www.kernel.org/doc/Documentation/networking/tuntap.txt

**Comment by surereddy** [comment]
Sir i have this issue client cannot run 

vpn  --port 9050  --server-addr 5.79.106.222 --disable-crypto

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by surereddy** [comment]
sorry its my mistake  it runs but there is no internet on client machine 

vpn  --server-addr 5.79.106.222:9050 --disable-crypto
[2018-02-11 18:49:17.318663250  INFO] vpn use default interface "eth0"
[2018-02-11 18:49:17.318888176  INFO] vpn bind on interface eth0 159.89.188.16:9050
[2018-02-11 18:49:17.318966355  INFO] vpn connect to 5.79.106.222:9050 with timeout 10s
[2018-02-11 18:49:17.407939142  INFO] vpn tun device running at 172.16.0.7 --> 172.16.0.1 netmask: 255.255.0.0
packet_write_wait: Connection to 159.89.188.16 port 22: Broken pipe

**Comment by LuoZijun** [comment]
reconnect `159.89.188.16:22` .

**Comment by surereddy** [comment]
where should i write this command reconnect 159.89.188.16:22 please

**Comment by LuoZijun** [comment]
i don't know.
