### ISSUE TITLE
License restrictions?

### ISSUE THREAD

**Issue by naltun** [LuoZijun/exodus#20]
First off, wonderful project. I'm curious about what the license agreement is when using this software, as I don't see a mention of licensing.

**Comment by LuoZijun** [comment]
See https://github.com/LuoZijun/exodus/blob/master/LICENSE

**Comment by naltun** [comment]
Awesome. I'll close this issue. Good luck with development!

**Comment by LuoZijun** [comment]
Thank you!

This project will move to https://github.com/ExodusVPN . The code will also refactor.
