### ISSUE TITLE
mac上，运行启动命令遇错

### ISSUE THREAD

**Issue by briteming** [LuoZijun/exodus#21]
hi.

```
bogon:~ brite$ ./vpn_macos-ar.sh
Password:
[2018-08-13 10:58:16.970506000  INFO] vpn use default interface "en0"
[2018-08-13 10:58:16.971483000  INFO] vpn bind on interface en0 192.168.1.104:9050
[2018-08-13 10:58:16.971530000  INFO] vpn connect to my-vps-ip:9050
thread 'main' panicked at 'recv function failed: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
bogon:~ brite$ cat vpn_macos-ar.sh
sudo ./vpn_macos_oldest --server-addr my-vps-ip:9050 --disable-crypto
bogon:~ brite$
```

怎么解决？

**Comment by LuoZijun** [comment]
@briteming 

目前暂不支持域名解析，只支持IP地址。所以将 `my-vps-ip` 改成 IP 应该就没有问题了。

**Comment by LuoZijun** [comment]
@briteming 如果该问题依然没有解决，你可以重新打开这个 ISSUE.

**Comment by luckypoem** [comment]
hi.
我没有使用域名。我用的是服务器的IP。我在另一台 vps上运行了你这个程序。不过运行本地的程序还是遇错，同样的错误，重启mac后，再运行还是一样。
bogon:~ brite$ sudo ./vpn_macos_oldest --server-addr my-vps-ip:56367 --disable-crypto
[2018-09-25 05:54:11.990357000  INFO] vpn use default interface "en0"
[2018-09-25 05:54:11.991138000  INFO] vpn bind on interface en0 192.168.1.104:9050
[2018-09-25 05:54:11.991173000  INFO] vpn connect to my-vps-ip:56367
thread 'main' panicked at 'recv function failed: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
bogon:~ brite$

如何解决？

**Comment by LuoZijun** [comment]
@luckypoem 服务端和客户端不可以在同一台服务器运行。

**Comment by luckypoem** [comment]
hello,
我在mac上运行了客户端命令，最后显示：
[2018-10-05 15:10:14.588687000  INFO] vpn Ready for transmission.

但是就是翻墙失败，我查看了mac系统的dns server已经变成了8.8.8.8,但是用这个vpn翻墙还是失败。（浏览器我已设为直连），不知为什么？以前都是成功的，现在却失败了，怪事

**Comment by luckypoem** [comment]
在chrome浏览器的左下方总是显示“正在解析主机”，

**Comment by LuoZijun** [comment]
@luckypoem 

1. 可以尝试重启下服务端，然后再看看，客户端连服务端会申请一个内网IP地址，这个我是写成了自增的，也有可能突破了子网上限。我当时想，可能需要连几万次才会出现这样的情况，就没在意。
2. 尝试使用网络抓包工具看下网络通讯。

**Comment by luckypoem** [comment]
重启下服务端后，果然正常了

**Comment by luckypoem** [comment]
hi.
我的safari的代理设置最近变成了不可用状态（灰色）：
偏好设置-高级-更改设置-代理，显示为不可用状态（灰色）。如何把它变成可用状态？
非常感谢你的答复

**Comment by LuoZijun** [comment]
我不太清楚这个，据我所知，Safari 的代理是遵循系统的配置，所以你可以前往系统配置里面配置代理，Safari 不需要有任何配置。

> 打开系统全局菜单 --> 系统便好设置 --> 网络 --> 选择当前状态为“激活”状态的网络设备（如: Wi-Fi 或者 雷雳网桥） --> 在右下角点开 “高级” 选项 --> 在横栏菜单选择 “代理” 标签 --> 然后根据你的代理情况选择勾上一个代理选项（如：SOCKS代理） --> 然后填写相关的代理信息 --> 最后点“保存” 即可

<img width="644" alt="image" src="https://user-images.githubusercontent.com/717717/46657635-4f1b3d00-cbe3-11e8-88d6-22c4858607b1.png">

**Comment by luckypoem** [comment]
"Safari 的代理是遵循系统的配置"没错，跟safari的“偏好设置-高级-更改设置-代理”弹出的图其实是同一个图。
你这个嵌入的图，我在自己的mac上打开了，它是这个样子：
http://2.bp.blogspot.com/-AddPwZWl7-Q/XoC8-6BcRrI/AAAAAAAADxI/dddupbKy6m4rjA8IWa0B75GVZQfnavFZACK4BGAYYCw/s1600/%25E5%25B1%258F%25E5%25B9%2595%25E5%25BF%25AB%25E7%2585%25A7%2B2020-03-29%2B%25E4%25B8%258B%25E5%258D%258811.15.33.png

还是灰色的，socks代理那一行是我启动shadowsocksX后，被shadowsocksX自动修改的。退出shadowsocksX后，socks代理那一行的钩就自动去掉了，socks代理服务器的值也自动清空了。我不清楚shadowsocksX是用什么命令修改mac系统的代理配置的？
另外，如何把mac系统的代理配置窗口变成可用状态？
非常感谢你的答复。
