### ISSUE TITLE
unable to build with openssl 1.1.1 as hyper-tls is too old

### ISSUE THREAD

**Issue by contrun** [LuoZijun/exodus#23]
I got this error while running `cargo build`
```
   Compiling openssl v0.9.24
   Compiling tokio-threadpool v0.1.14
   Compiling logging v0.1.0 (/home/e/Local/exodus/logging)
   Compiling phf_generator v0.7.24
   Compiling mio-uds v0.6.7
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/e/Local/exodus/target/debug/build/openssl-25e0f4547135f68b/build-script-build` (exit code: 101)
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/e/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

My symptom is exactly the same as [this issue](https://github.com/sfackler/rust-openssl/issues/994).
It seems that the the dependency `hyper-tls` is so old that it requires the old-fashioned openssl v0.9.24.

**Comment by LuoZijun** [comment]
@contrun 目前已经开始重写了。

加密库这块，已经不再依赖 `openssl` 和 `ring` 了。

支持的算法:

*    ChaCha20-Poly1305
*    Ed25519
*    AES-SIV

https://github.com/ExodusVPN/exodus/tree/rewrite/crates/crypto
