### ISSUE TITLE
如何在运行mac上的客户端命令后，就自动把mac的dns server改为208.67.222.222？

### ISSUE THREAD

**Issue by luckypoem** [LuoZijun/exodus#24]
hi.

sudo ./vpn_macos --server-addr my-vps-ip:56367 --disable-crypto

运行完此命令后，就自动把mac的dns server改为了8.8.8.8,那么“如何在运行mac上的客户端命令后，就自动把mac的dns server改为208.67.222.222？”

**Comment by LuoZijun** [comment]
```bash
sudo networksetup -setdnsservers "Wi-Fi" "DNS-IP"
```
