### ISSUE TITLE
没有看懂这个能干啥

### ISSUE THREAD

**Issue by lizhaode** [LuoZijun/exodus#3]

**Comment by LuoZijun** [comment]
目标功能：

1. 全局VPN
2. 全局IP层代理
3. 全局TCP/UDP代理

至于介绍，考虑到功能没有完善，所以暂时不加。

**Comment by LuoZijun** [comment]
@lizhaode alpha 版本已经发布 https://github.com/LuoZijun/exodus/releases/tag/alpha ，说明文件也已更新，可以在 `release` 里面直接下载已编译好的二进制文件，也可以参考说明文档自行编译。

**Comment by lizhaode** [comment]
就是根目录下的README吗？只是添加了编译的方法，还是没有详细的文档介绍啊

特别是，没有中文.......

**Comment by LuoZijun** [comment]
@lizhaode 请自行谷歌关键字 “VPN/Proxy”，普及这些知识点并不是这个项目的初衷。
