### ISSUE TITLE
这个VPN有什么优势？What‘s better about this VPN?

### ISSUE THREAD

**Issue by Humilton** [LuoZijun/exodus#4]
这个VPN有什么优势？What‘s better about this VPN?

**Comment by LuoZijun** [comment]
@Humilton 

相比较传统的 VPN( IPsec/OpenVPN ): 

1. 这款 VPN 无协议特征（当前版本依然有协议特征）。
2. 代码量万行不到（相比较下 OpenVPN 有将近三十万代码）
3. 高度集成，相比较下，OpenVPN 需要配合 `tuntap` 独立组件工作。
4. 零配置（Routing table, NAT, tuntap）

**Comment by LarryBrin** [comment]
Can this VPN works on Mac well? 
And whether the speed is fast enough, like surfing softly for Youtube?
这个VPN在Mac上可以正常持续地工作吗？
速度是否足够快，比如是否支持在YouTube上流畅地看高清视频？（带宽100Mbs）

**Comment by LuoZijun** [comment]
@LarryBrin 支持 macOS/Linux .

我自己也是 macOS 客户端， Linux 服务端，也是百兆带宽，看 Youtube 4K 视频没有问题。

不过速度还是取决于你的 VPS 。

我自己使用的是 Google Cloud 东京区，延迟为 32ms。

**Comment by agaolong** [comment]
没有windows和安卓的使用说明，是不支持吗？

**Comment by LuoZijun** [comment]
@chengziqing 是的，暂时支持macOS和Linux。
