### ISSUE TITLE
用你这个vpn程序翻不了墙了

### ISSUE THREAD

**Issue by briteming** [LuoZijun/exodus#41]
昨天。今天，尝试使用它，都失败了：
sudo ./vpn_macos_oldest --server-addr vps-ip:56367 --disable-crypto

感觉是gfw升级了而你这个vpn程序没用启用加密的缘故。何时能推出加密版本？何时能用上参数‘--enable-crypto'?

**Comment by LuoZijun** [comment]
错误信息是什么？
一般来说，不可以用了，可能是IP的通讯受到了干扰。这种干扰加密了也没有用。

**Comment by briteming** [comment]
没有错误信息。仍然是：
vpn Ready for transmission.
但就是翻不了墙。

**Comment by briteming** [comment]
我服务器的IP的通讯并未受到干扰，因为我用其他翻墙术都能正常翻墙

**Comment by briteming** [comment]
今天又可以翻墙了，抽风啊

**Comment by LuoZijun** [comment]
好吧

**Comment by briteming** [comment]
今天试了，又不行了。已改用wireguard

**Comment by briteming** [comment]
hi.
你那边还可用这个vpn程序翻墙吗

**Comment by LuoZijun** [comment]
@briteming 我一般都是直接使用的 ssh 反向代理。除了非常特殊的需要全局的我才临时使用这个。

翻墙失败，也会跟你的 VPS 网络质量（不是单纯的通迅质量）有关。

即便是 Shadowsocks 也会如此，一般便宜的 VPS 都会出现这种情况。

我使用的是价格算是比较贵的，从来就没出现过这种情况。

**Comment by briteming** [comment]
'我使用的是价格算是比较贵的",
which vps  provider do u use？

**Comment by LuoZijun** [comment]
腾讯（香港）和谷歌（台湾）。

**Comment by briteming** [comment]
hi.

"用你这个vpn程序翻不了墙了"的原因原来是我没有开放服务器上的exodus的端口，开放后就可以翻墙了，但是有部分网站还是无法访问，比如dongtaiwang.com, fc2.com, 不知为什么，如何解决问题？
