### ISSUE TITLE
cargo build --release遇错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [LuoZijun/exodus#7]
hi.

root@RegalMusty-VM:~/exodus# cargo build --release
warning: unused manifest key: profile.dev.incremental
warning: unused manifest key: profile.release.incremental
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/rust-lang/libc`
    Updating git repository `https://github.com/LuoZijun/nix`                   
error: failed to load source for a dependency on `nix`                          

Caused by:
  Unable to update https://github.com/LuoZijun/nix?branch=patch-4

To learn more, run the command again with --verbose.
root@RegalMusty-VM:~/exodus#

**Comment by LuoZijun** [comment]
@luckypoem 请 `git pull` 拉取最新代码，因为 `patch-4` 已被上游合并，所以我这边的已经删除该分支。

```bash
git pull
cargo update
cargo build --bin vpn --release
cargo build --bin vpnd --release
```

**Comment by luckypoem** [comment]
我这里先下载了你的executable文件。
在mac上，

yudeMacBook-Air:~ brite$ ./vpn_macos --server-addr my-vps-ip:9050 --disable-crypto 
[2018-01-14 18:49:10.425625000  INFO] vpn use default interface "en0"
[2018-01-14 18:49:10.426711000  INFO] vpn bind on interface en0 192.168.1.3:9050
[2018-01-14 18:49:10.426786000  INFO] vpn connect to my-vps-ip:9050
thread 'main' panicked at 'can't create tun device.: Error(Io(Error { repr: Os { code: 1, message: "Operation not permitted" } }), State { next_error: None, backtrace: None })', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
yudeMacBook-Air:~ brite$ 

怎么解决？

**Comment by LuoZijun** [comment]
@luckypoem 请仔细阅读 `README.rst` 文件，客户端执行需要 `sudo` 。

**Comment by luckypoem** [comment]
是的，sudo一下就ok了。
非常感谢你开发的这个vpn!

**Comment by LuoZijun** [comment]
@luckypoem 不客气。

**Comment by luckypoem** [comment]
yudeMacBook-Air:~ brite$ sudo ./vpn_macos --server-addr my-vps-ip:9050 --disable-crypto
Password:
Can't get default networkservice.
yudeMacBook-Air:~ brite$ 

怎么解决Can't get default networkservice？

**Comment by LuoZijun** [comment]
@luckypoem 

把 这几个 命令执行，并在新的 ISSUE 里面 贴上输出（对应相应的命令）

```bash
ifconfig
route -n get default

networksetup -listallnetworkservices
networksetup -listnetworkserviceorder

uname -a
```

最后贴上你的操作系统和版本。

不要在继续在这个问题里面贴。

**Comment by luckypoem** [comment]
我重启mac机器，再运行该命令：sudo ./vpn_macos --server-addr your-vps-ip:9050 --disable-crypto
就解决问题了

**Comment by LuoZijun** [comment]
请不要再在这个问题上面报告无关的事情，谢谢。
